Feature/1 simpacc UI
dnycstr/simpacc-accounting-ui pull request #11
Opened 2023-08-15 15:22 UTC by chemstone143

- [ ] Refactor elements (Buttons, InputText, and the likes) into a separate and reusable react components.
- [ ] Make a sidebar menu as required by Simpacc team
- [ ] Test SyncFusion Grid.[ Click this to see example grid](https://ej2.syncfusion.com/react/demos/#/tailwind/grid/overview)
- [ ] Make the design responsive for small, medium, large design. [See this](https://github.com/dnycstr/simpacc-accounting-ui/pull/11#issuecomment-1680383124)

2023-08-16 10:41 UTC, dnycstr requested changes

2023-08-16 10:41 UTC, dnycstr commented on README.md
> +yada yada ydaa
Clean this up guys

2023-08-16 10:41 UTC, dnycstr commented on src/modules/billing/pages/Revenue and Collections/Products&Services.tsx
Avoid using [SPACE] and Special Characters such as '&' for foldernames and filenames.

2023-08-16 10:41 UTC, dnycstr commented on src/modules/billing/pages/Reports/Profit&Loss/Comparative.tsx
Avoid & in Foldername.

Rename the folder to "ProfitAndLoss"

2023-08-16 10:41 UTC, dnycstr commented on src/modules/billing/pages/PurchaseandPayments/Vendors.tsx
Rename PurchaseandPayments to "PurchaseAndPayments"

2023-08-16 10:41 UTC, dnycstr commented on src/modules/billing/pages/Reports/Profit&Loss/YeartoDate.tsx
Rename this to "YearToDate.tsx"

2023-08-16 10:41 UTC, dnycstr commented on src/modules/billing/AppRouter.tsx
> +      { path: 'purchase-&-payments/vendors', element: <Vendor /> },
Do not use '&' for path. Replace this with "purchase-and-payments". & character has special meaning in URLs.

2023-08-16 10:46 UTC, dnycstr commented
The design looks good on Desktop now. Nice work 👍

2023-08-16 10:51 UTC, dnycstr commented
Make the design responsive for smaller device.
![image](https://github.com/dnycstr/simpacc-accounting-ui/assets/11267927/1de35978-bedd-4dc1-9479-9664d8bc84b8)

2023-08-21 12:46 UTC, Jheyem0212 approved these changes

2023-08-21 12:46 UTC, merged